### ISSUE TITLE
Add config file

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Styleguide#1]
Styleguide component should have config.json file with following options:
- **admin Domains** - a list of domains that allows to show edit functionality
- **categories** - a list of categories of the snippets with unique id
- **watch urls** - a list of pages that can be scraped or used for performance testing
- **css resources** - [future feature] we need to provide project's css assets. We can scrape them directly from the site but then we need to define which domain is the main one.
- **path to styleguide**
- **path to scss variables file**

**Comment by gediminas-s** [comment]
Edit functionality can be determined by if node.js server is running on the machine.

**Comment by miezis** [comment]
Fixed, done.
