### ISSUE TITLE
PostCSS Support

### ISSUE THREAD

**Issue by stephenway** [devbridge/Styleguide#104]
Hey I just ran across this project and really like the direction you've taken it. As a user of PostCSS, I'm wondering if I would run into issues if I tried this? The features look like they are geared towards Sass.

**Comment by gediminas-s** [comment]
Hi Stephen,
To work with the Styleguide you need to add references of already compiled CSS resource. PostCSS should not affect styleguide workflow. The only place where you can have issues is variables scraping. PostCSS have extension for scss syntax that should help (https://github.com/postcss/postcss-scss) but it needs to be tested. So, if you are not bundling your css with js, you should be fine using PostCSS with this tool. 
Let us know how it go's.

**Comment by stephenway** [comment]
Thanks! Do you think native CSS variable support is in the future?

**Comment by gediminas-s** [comment]
Not yet but most likely we will add native CSS variables support in the future.
