### ISSUE TITLE
Styleguide Initialize issue

### ISSUE THREAD

**Issue by BrandenA** [devbridge/Styleguide#106]
After installing styeguide to my project directory and gloablly running "styleguide initialize" returns " : No such file or directory".

**Comment by christhorp** [comment]
Me too

env: node\r: No such file or directory

**Comment by valiooo** [comment]
Can you give me more details what exact steps you made to get to this point. My guess is that you are not running `styleguide initialize` command inside your project directory.

**Comment by VaclovasV** [comment]
@christhorp what node version are you using?
Please, provide more information. OS, node version and other details would be helpful.

**Comment by christhorp** [comment]
I've got node version 4.2.1, on OS X. When you say in should be in the project directory, what does this mean exactly? What files should be in there?

**Comment by miezis** [comment]
@christhorp There should be node_modules directory from where the command is being run.

**Comment by christhorp** [comment]
Oh yeah, of course. I wasn't sure it needs to have an index.html, or a css file in a relative position for it to work.

**Comment by christhorp** [comment]
I quick google suggests it might be something to do with being created on a different OS? http://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo

**Comment by gediminas-s** [comment]
@christhorp , i was able successfully run current styleguide version on Mac with Node v.4.2.1
Just to make sure you follow steps:
After you install styleguide locally (your project directory) and globally, in terminal navigate to your project root directory (cd /.../) and when run `styleguide initialize`. New folder with the name /styleguide/ should appear in your project root dir.

**Comment by BrandenA** [comment]
Used NPM to update Node. Styleguide working as intended.,

**Comment by VaclovasV** [comment]
@gediminas-s - we should add node version to requirements

**Comment by christhorp** [comment]
I've just upgraded node to 5.2.0. Still the same problem. I'm definitely inside the project directory when I run styleguide initialize! Any other ideas? I would really like to try this.

**Comment by kristenakamura** [comment]
I am also having this problem. I tried with node 4.4.4 and 6.1.0, reinstalling the packages each time.
