### ISSUE TITLE
Error: Not Found when start styleguide

### ISSUE THREAD

**Issue by elumbroso** [devbridge/Styleguide#109]
Hello,

I did all steps without any errors, but when I run gulp start-styleguide, and I go on http://localhost:8080/styleguide/index.html, I have this message : "Error: Not Found at (...path to node_modules/.../app.js:36) ".

Did I miss something...? 

Thank you for your help.

**Comment by VaclovasV** [comment]
1. Do you have node_modules in your project root?
2. Do you have styleguide folder generated into your project root?

**Comment by elumbroso** [comment]
Yes & Yes

**Comment by miezis** [comment]
http://localhost:8080 - is this your projects url or styleguides? Because the styleguide static files should be served with your project, gulp start-styleguide only enables API for editing snippets and scraping variables.

**Comment by nguyenmanh1507** [comment]
You need start your own http server. If you using gulp, you can install [browser-sync](https://www.browsersync.io/). If you need fast and easy way, just using [live-server](https://github.com/tapio/live-server).

**Comment by donovanh** [comment]
Having the same issue here. Tried running it with Pow also rather than locahost:8080 and no luck.

**Comment by miezis** [comment]
My guess is that you are trying to reach your styleguide through hostname that exposes only styleguide API.

As it was mentioned - your styleguide static files should be served by your project server, as we can see from readme:

You should access your styleguide going to http://your-project-hostname/styleguide/index.html

**Comment by donovanh** [comment]
Oh, very cool! Ok, so I got it working this way. My project is an Express app with a `public` directory for static assets. I ran `styleguide initialize public/styleguide` then in the Gulp example, specified the URL. That got it going. Thanks for the pointers.

**Comment by miezis** [comment]
@elumbroso did it work for you?

**Comment by VaclovasV** [comment]
@gediminas-s @miezis, maybe we should add this to documentation?

**Comment by WhatsNewSaes** [comment]
I'm running into the same issue. Installed everything, initialized the styleguide, I see it in my project root, but when I run `gulp start-styleguide` I get the following message in my terminal

```
[14:12:50] Starting 'start-styleguide'...
[14:12:50] Finished 'start-styleguide' after 6.17 ms
Styleguide server listening on port 8080
Error: Not Found
``` 

Any ideas?

**Comment by heronblade** [comment]
I think this issue will pop up if you're just downloading styleguide to test it out and see how it works.

I had the same issues that @elumbroso had when I first installed.  To fix it do the following.

1. Install [live-server](https://github.com/tapio/live-server)
2. Run the command `live-server` from inside the directory with the styleguide folder
3. Once live-server is up and running, run the gulp task to start up styleguide
4. Go to `http://127.0.0.1:8080/styleguide/index.html` and you should see the styleguide up and running.

It'd be nice if this could be added to the README.

**Comment by elumbroso** [comment]
Yes, it's working. Thank you for your explanation ! :)
