### ISSUE TITLE
Readme needs work

### ISSUE THREAD

**Issue by stevieg83** [devbridge/Styleguide#114]
Cloned the repo, went to run `npm install devbridge-styleguide --save-dev`

and got 

> npm ERR! Darwin 15.4.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "devbridge-styleguide" "--save-dev"
> npm ERR! node v5.10.1
> npm ERR! npm  v3.8.3
> npm ERR! code ENOSELF
> 
> npm ERR! Refusing to install devbridge-styleguide as a dependency of itself
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/steven/Frontend/triservicereg/npm-debug.log

**Comment by gediminas-s** [comment]
You are trying to install styleguide inside itself.
You don't need to clone the repo because copy of it resides on npm. Just create empty project, in your CLI navigate to your project root directory and run `npm install devbridge-styleguide --save-dev`.
