### ISSUE TITLE
Support to Stylus

### ISSUE THREAD

**Issue by danilovaz** [devbridge/Styleguide#119]
I'm trying to use Styleguide in my Ember.js project, but unsucessfuly because I'm using Stylus. Has any chance to include support to Stylus in the next releases?

**Comment by danilovaz** [comment]
That's amazing! I will test this way. Ty :smiley:

**Comment by langermank** [comment]
Do you have an idea of when Stylus or LESS might be supported?

**Comment by LFeh** [comment]
+1 to add the support of Stylus \o

**Comment by Arkkimaagi** [comment]
+1 for LESS-file support

**Comment by gediminas-s** [comment]
#143 task created.
