### ISSUE TITLE
scraping sass partials

### ISSUE THREAD

**Issue by sensaetions** [devbridge/Styleguide#124]
Hello, is it possible for the styleguide to scrape sass partials? I tried creating sass partials and importing it into my main sass file, and the styleguide couldn't scrape it. It looks like the variables has to be in the main sass file in order for the guide to scrape it.

I like using sass partial as it helps break up the styling and is easier to maintain.

**Comment by miezis** [comment]
Did you define path to your partial in config?

**Comment by sensaetions** [comment]
Do I have to define the partials individually, or is globbing suopported? What would the path be for `"sassVarables" : []` if my folder structure is:

```
- assets/sass/variables/_colors.scss
- styleguide
```

**Comment by miezis** [comment]
It only works individually, it should be:

"sassVariables": ["./assets/sass/variables/_colors.scss", "assets/sass/variables/_typography.scss"]

**Comment by sensaetions** [comment]
I included the sass partials as you instructed. However, when I go to scrape the variables, I get the **Scrape **Report** error `Failed to scrape sass! Maybe your styleguide server is down?`

The server is still running. Terminal errors read:

```Typography markers not found in assets/sass/variables/_colors.scss.
Color markers not found in assets/sass/variables/_type.scss.
TypeError: Cannot convert undefined or null to object```

even though the smart comment tags and sass variables exists in those two files. So it looks like sass partials or multiple sass files is not supported?

**Comment by sensaetions** [comment]
Also, is there further documentation on how to create other sections of the styleguide? Or do I need to use the GUI to create snippets?

**Comment by miezis** [comment]
Is there a stack trace of that error? And I don't understand the question about other sections.

**Comment by sensaetions** [comment]
By stack trace of that error, is this what you mean?

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at compareForReport (/Users/path-to-styleguide-project/node_modules/devbridge-styleguide/routes/sassScraper.js:210:33)
    at Object.exports.scrapeTheme (/Users/path-to-styleguide-project/node_modules/devbridge-styleguide/routes/sassScraper.js:245:3)
    at /Users/path-to-styleguide-project/ras-styleguide/node_modules/devbridge-styleguide/routes/scrape.js:127:29
    at Layer.handle [as handle_request] (/Users/path-to-styleguide-project/ras-styleguide/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/path-to-styleguide-project/ras-styleguide/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/path-to-styleguide-project/ras-styleguide/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Users/path-to-styleguide-project/ras-styleguide/node_modules/express/lib/router/layer.js:82:5)
    at /Users/path-to-styleguide-project/ras-styleguide/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/Users/path-to-styleguide-project/ras-styleguide/node_modules/express/lib/router/index.js:321:12)
```

**Comment by sensaetions** [comment]
In regards to the other sections question, your styleguide demo shows "Form Elements", "Headings", "Modules", etc, that has "Field input", "Select box", etc. 

How would I go about creating those other elements? Is there more documentation on creating those, or do I just use the generated styleguide "snippets" to create those elements?

**Comment by miezis** [comment]
Thanks for stack trace of the error, I'll investigate that.

Those other sections are categories - you can create them from UI.
