### ISSUE TITLE
`Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by DoorDarius** [devbridge/Styleguide#126]
Hello!

I can't seem to be able to scrape the variables on Windows 10. The error I keep getting:

> Failed to scrape sass! Maybe your styleguide server is down?

`
> Error: EISDIR: illegal operation on a directory, read
>     at Error (native)
>     at Object.fs.readSync (fs.js:651:19)
>     at Object.fs.readFileSync (fs.js:472:24)
>     at Object.exports.scrapeTheme (D:\Projects\Projectname\node_modules\devbridge-styleguide\routes\sassScraper.js:224:13)
>     at D:\Projects\Projectname\node_modules\devbridge-styleguide\routes\scrape.js:127:29
>     at Layer.handle [as handle_request] (D:\Projects\Projectname\node_modules\express\lib\router\layer.js:82:5)
>     at next (D:\Projects\Projectname\node_modules\express\lib\router\route.js:110:13)
>     at Route.dispatch (D:\Projects\Projectname\node_modules\express\lib\router\route.js:91:3)
>     at Layer.handle [as handle_request] (D:\Projects\Projectname\node_modules\express\lib\router\layer.js:82:5)
>     at D:\Projects\Projectname\node_modules\express\lib\router\index.js:267:22
> `

Logo, Site and name do work

My config:
`{
  "projectName": "Project",
  "projectUrl": "http://www.project.nl",
  "projectLogo": "/styles/default/images/logo.png",
  "jsResources": [],
  "viewportWidths": [
    320,
    480,
    768,
    1024
    1280
  ],
  "serverPort": 4500,
  "snippetTemplate": "styleguide/template.html",
  "sassVariables": "/_sources/default/sass/variables.scss",
  "maxSassIterations": 2000,
  "database": "styleguide/db",
  "categories": "styleguide/db/categories.txt",
  "uniques": "styleguide/db/uniques.txt",
  "sassData": "styleguide/db/sassdata.txt",
  "extension": ".txt"
}

**Comment by miezis** [comment]
sassVariables has to be an array of strings.

**Comment by DoorDarius** [comment]
Thought I tested this, apparently I had more errors back then. This fixed the scraping.
