### ISSUE TITLE
Show warning message when invalid (css/html) snippet is submitted for the first time

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Styleguide#13]
For the first time, show warning message and prevent snippet submission. Let user force snippet submission on his own risk.

**Comment by gediminas-s** [comment]
If I understand correctly, you want to show warning message but let user to submit invalid snippet? What is the use case for this?

**Comment by VaclovasV** [comment]
Ace editor can return if html/css is valid in snippet. Sometimes, user may want to add invalid snippet (can be some scenarios, then user will want to use invalid css/html), so I think, we should let him do this, but warn him, that this can be harmful. 
I'm not sure if we need functionality to "force invalid" snippet, but i think, displaying message to user then snippet is invalid - would be useful. We can prevent issues like in betterCms, then invalid html breaks all the page.

**Comment by gediminas-s** [comment]
understood, go for it :)

**Comment by miezis** [comment]
Implemented.
