### ISSUE TITLE
When creating new snippet, caret not visible while editing in "Code" and "Inline CSS" views

### ISSUE THREAD

**Issue by markplewis** [devbridge/Styleguide#137]
When you create a new snippet, the caret is invisible while editing in "Code" and "Inline CSS" views. In contrast, when you edit an existing snippet, the caret is visible inside the text editor, so you can clearly see where you are inserting text. I'm able to replicate this issue in Chrome 50 (Mac), Safari 9.1 and Firefox 45 (Mac).

**Comment by gediminas-s** [comment]
On it.

**Comment by gediminas-s** [comment]
Fixed and merged to master.
