### ISSUE TITLE
Scrollbars always displayed

### ISSUE THREAD

**Issue by krja1012** [devbridge/Styleguide#138]
Hi,
how it is possible to get rid of the scrollbars?
They're always displayed and haven't got any functionality.

![capture_20160429_091902](https://cloud.githubusercontent.com/assets/3943005/14910173/73d7290a-0deb-11e6-8c32-46144e123fdc.png)

Thanks!

**Comment by gediminas-s** [comment]
Could you give us more details:
- what OS, browser you are on?
- snippet code would be useful
- any specific CSS in your snippet?

**Comment by krja1012** [comment]
Sorry for that.

OS: Win 8.1 64bit
Browser: newest Chrome and FF
no specific CSS
Snippet-Code: 

`<div class="g-card g-card--shadow">
    <div class="g-card__header">
        <div class="g-layout">
            <div class="g-layout__item">
                <span class="g-card__title">Card - Titel</span>
            </div>
        </div>
    </div>
    <div class="g-card__block">
        <div class="g-layout g-layout--quarter">
            Lorem...
	</div>
    </div>
</div>`

Is it possible that the scrollbars are results of my own css sheet although I never use scrollbars anywhere on my page?

**Comment by gediminas-s** [comment]
I was unable to replicate your issue, most likely it's related to your project's css.
