### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by ebowers** [devbridge/Styleguide#139]
Hey there,

I wasn't really sure where I could go for help on the setup for this, but I'm running into an error on installation and am curious where I am going wrong.

I went through and followed the steps for installation, `styleguide-initialize` was successful.

I added the task to my gulpfile, and included it in my default task so that it runs at the same time as my browser sync server. When I view the root `localhost:3000` everything is fine, but when I view `localhost:3000/styleguide` I get a **Cannot GET /styleguide/** error.

I assume this is maybe a gulp setup issue, but would anyone mind helping me out?
## Project Setup:

```
projectName/
|- dist/
|- src/
|- styleguide/
|  |- content/
|  |- db/
|  |- js/
|  |- config.txt
|- gulpfile.js
|- index.html
|- package.json
```
## Gulpfile:

```
var gulp = require('gulp'),
    plumber = require('gulp-plumber'),
    rename = require('gulp-rename');
var autoprefixer = require('gulp-autoprefixer');
var concat = require('gulp-concat');
var uglify = require('gulp-uglify');
var imagemin = require('gulp-imagemin'),
    cache = require('gulp-cache');
var minifycss = require('gulp-minify-css');
var sass = require('gulp-sass');
var browserSync = require('browser-sync');
var styleguide = require('devbridge-styleguide');

gulp.task('browser-sync', function() {
  browserSync({
    ui: {
      port: 3001
    },
    server: {
       baseDir: "./"
    }
  });
});

gulp.task('bs-reload', function () {
  browserSync.reload();
});

gulp.task('start-styleguide', function () {
  styleguide.startServer();
});

gulp.task('images', function(){
  gulp.src('src/images/**/*')
    .pipe(cache(imagemin({ optimizationLevel: 3, progressive: true, interlaced: true })))
    .pipe(gulp.dest('dist/images/'));
});

gulp.task('styles', function(){
  gulp.src(['src/styles/**/*.scss'])
    .pipe(plumber({
      errorHandler: function (error) {
        console.log(error.message);
        this.emit('end');
    }}))
    .pipe(sass())
    .pipe(autoprefixer('last 2 versions'))
    .pipe(gulp.dest('dist/styles/'))
    .pipe(rename({suffix: '.min'}))
    .pipe(minifycss())
    .pipe(gulp.dest('dist/styles/'))
    .pipe(browserSync.reload({stream:true}))
});

gulp.task('scripts', function(){
  return gulp.src('src/scripts/**/*.js')
    .pipe(plumber({
      errorHandler: function (error) {
        console.log(error.message);
        this.emit('end');
    }}))
    .pipe(concat('main.js'))
    .pipe(gulp.dest('dist/scripts/'))
    .pipe(rename({suffix: '.min'}))
    .pipe(uglify())
    .pipe(gulp.dest('dist/scripts/'))
    .pipe(browserSync.reload({stream:true}))
});

gulp.task('default', ['browser-sync', 'start-styleguide'], function(){
  gulp.watch("src/styles/**/*.scss", ['styles']);
  gulp.watch("src/scripts/**/*.js", ['scripts']);
  gulp.watch("*.html", ['bs-reload']);
});
```

**Comment by VaclovasV** [comment]
@ebowers , this is already mentioned in documentation: 

> Note, the purpose of the styleguide server is to expose API for styleguide data manipulation ONLY. In order to view the styleguide in the browser, you need to setup and run your own project’s server. We recommend using simple http server - live-server.

use localhost:3001 to access styleguide

**Comment by ebowers** [comment]
@VaclovasV Thanks for the reply! I have Browsersync setup as a server and when I try to access localhost:3001/styleguide the page just loads the entire time and nothing happens. Any ideas?

**Comment by VaclovasV** [comment]
@ebowers - give source of your styleguide page (load styleguide url and copy everything from "view source")
more details would be helpful too:
screenshot of developers tools console, but I think, that issue is with setup, not with our component.

**Comment by gediminas-s** [comment]
@ebowers did you manage to run styleguide component?
