### ISSUE TITLE
Working with AngularJS and external libraries?

### ISSUE THREAD

**Issue by rubinchyk** [devbridge/Styleguide#140]
Hi guys. How this library working with UI components for example from Bootstrap 3 (if I'm using not all but some elements from this framework, and creating custom elements from scss), or D3 charts?
And can I use some JS like AngularJS and additional libraries?
Thank you for you work.

**Comment by VaclovasV** [comment]
@rubinchyk 
use template.html and include all additional resources here, they will be applied to snippet template.

Could you explain first question with more details provided? What do you want to achieve, because our styleguide component is framework agnostic.

**Comment by rubinchyk** [comment]
Thank you for answer, I think I have solutions for all my goals.

**Comment by MeLeGe** [comment]
Its cant working !! when i add some jquery or JS libraries in the head of template , i can`t see it in the page , Only the css code !!
