### ISSUE TITLE
Icons Missing 404 Error when running live-server

### ISSUE THREAD

**Issue by mplunkett5** [devbridge/Styleguide#141]
Hey, thanks for producing this.

I have tried setting this up today following your instructions and I hit issues with the icons. I had to redownload the fontawesome icon set as per #127 but I also had to manually download from your repo icons (icon-code-html.svg, icon-code-description.svg, icon-code-css.svg ).

**Comment by miezis** [comment]
Closed with https://github.com/devbridge/Styleguide/commit/bfb67d61d6ac98f3f342a692ca83986a3e4ef39f
