### ISSUE TITLE
Add support for Stylus and Less

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Styleguide#143]

**Comment by dasmurphy** [comment]
Just a tip: Temporary support for less is done in gulp for me with
[https://github.com/steelydylan/gulp-less-to-scss](https://github.com/steelydylan/gulp-less-to-scss)

It's easy to convert one or more (concat) less file(s) with the colors+fonts and import the generated file in Styleguide.
Thanks for the awesome tool.
