### ISSUE TITLE
Inline JavaScript

### ISSUE THREAD

**Issue by sebald** [devbridge/Styleguide#144]
I have some (Angular) components that require JavaScript to be rendered correctly.
Is it possible to put inline JavaScript inside Snippets?

The `jsResources` doesn't really do the job, because it will only hold the logic. I need to manually bootstrap the "app" to render components.

**Comment by sebald** [comment]
Nevermind, I found a working solution :)

**Comment by yumyo** [comment]
@sebald could you please give me some hints on how you managed to add inline javascript?

**Comment by sebald** [comment]
@yumyo of course :)

Basically, I have a setup a second build pipline (with webpack) that builds only the UI Components + some "example apps" and bundles them into one file called `examples.js`. The file is contained inside the `styleguide` folder and is loaded via `config.txt` settings (`jsResources`).

Your snippet will then have access to the JS. We do bootstrap some example Angular apps based on element IDs. The apps are super small and only contain some extra logic that is sometimes necessary to display a UI component. But I guess you should be able to whatever you want at this stage.
