### ISSUE TITLE
Styleguide Server

### ISSUE THREAD

**Issue by brandalist** [devbridge/Styleguide#148]
I'm running "styleguide server" but I'm not seeing any of controls, just the static pages. Any ideas?

**Comment by VaclovasV** [comment]
@brandalist  for some reason, server is not working :) open your developer console and see what message you will get "server is down" or "server is up"

**Comment by brandalist** [comment]
@VaclovasV 
You are right the "server is down" below is what the developer console reads. Any ideas why snippets/duplicates is not loading?
Failed to load resource: the server responded with a status of 404 (Not Found)
views.js: 582 
http://127.0.0.1:8080/snippets/duplicates
Server is down!

**Comment by miezis** [comment]
@brandalist That endpoint is used to determine if the server is running or not. Did you start the server?

**Comment by brandalist** [comment]
@miezis 
Not sure what is going on, but it seems like the server is looking for /snippets/duplicates and it can't find it. I think that's why the server is now running. Honestly, I don't know at this point.

**Comment by gediminas-s** [comment]
@brandalist did you manage to make it work?
If no, let's start from the start :)
After you started server, did you got message in cosnole "Styleguide server listening on port 8080". If yes, having you set up your http server? if yes, refreshing styleguide page (YourLocalHost/styleguide/) and going back to styleguide cosole, do you get any error messages. If yes, what they are?

**Comment by nynban** [comment]
Having the same problem and not working for me
I'm running "styleguide server" but I'm not seeing any of controls, just the static pages. Any ideas?
