### ISSUE TITLE
"\\" in config.txt brakes Firefox

### ISSUE THREAD

**Issue by mantas-kunsmanas** [devbridge/Styleguide#149]
"\\" in config.txt brakes Firefox 45.0.2 Windows
Error in console:
GET 
XHR 
http://localhost:5002/styleguide-admin%5Cdb%5Ccategories.txt
Firefox sees slashes as "/" not "\".

**Comment by VaclovasV** [comment]
@mantas-kunsmanas instead of  ` "uniques": "styleguide-admin\\db\\uniques.txt"`, just try to use 
 ` "uniques": "styleguide-admin/db/uniques.txt"` and etc. Long story short - switch "\\" to "/" and report is this fix helps

**Comment by VaclovasV** [comment]
@gediminas-s 
Lets test this on MacOS and if everything is ok - we should change default config and documentation

**Comment by VaclovasV** [comment]
Added changes to staging branch, need to test on macOS
