### ISSUE TITLE
mac permission problems? need to initialize styleguide everytime at a new mac machine?

### ISSUE THREAD

**Issue by novinaw** [devbridge/Styleguide#151]
We're aiming to use this in collaberation.  So we set it up running (from a windows machine) and share the folder.  

2nd machine (on a mac): got node running, gulp running, serve ... can't get to edit mode no matter what
the only way to get the edit mode is initialize styleguide again.  (OK, maybe just this mac).
3rd machine (on a mac) same problem.  

It's OK to initialize once, but if we share/git the styleguide folders with content, the initialization process would give it a fresh install wiping the styleguide everytime?

Is it something with our mac permissions?  or mac permissions in general?

**Comment by gediminas-s** [comment]
If I understand correctly, you have your styleguide's physical files on shared machine but you want to run styleguide locally. I would recommend to run styleguide server on shared machine but setup http server locally with references to remote machine.

**Comment by novinaw** [comment]
I believe you understood me correctly.  

The reason why we're trying to install it this way is because we're trying to integrate github so we can see each edit (who and by what) and have versions of it -- understanding that this is not a function devbridge's styleguide has.

Is there anyways to accomplish that?

**Comment by gediminas-s** [comment]
Did you guys manage to make it work?
