### ISSUE TITLE
Unable to initalize styleguide

### ISSUE THREAD

**Issue by Seanom** [devbridge/Styleguide#152]
I've installed both locally and globally (Steps 1 and 2) but unable to initialise the styleguide
`npm install devbridge-styleguide --save-dev`
`npm install devbridge-styleguide -g`

when I run step 3 `styleguide initialize`
I am running from inside the project directory

I get the following error message

    Missing required arguments: kssSource, styleSource, output
    Please provide sources of KSS files
    Please provide sources of preprocessed files
    Please provide output path
    

I managed to get it to initialise if I pass in those parameters but then get stuck with the same error as #117. The folder is created but the config.txt is not

What am I doing wrong?

**Comment by miezis** [comment]
You have another package, that is aliased as styleguide, my guess would be sc5-styleguide?

**Comment by Seanom** [comment]
ah good call, I've pruned npm and that seems to have solved that issue, now I get stuck on #153 

Thanks for the pointer
