### ISSUE TITLE
styleguide initialize command: nodejs error

### ISSUE THREAD

**Issue by mpons** [devbridge/Styleguide#153]
On OSX 10.11.3 while trying styleguide for the first time I encountered this issue with the ```styleguide initialize``` command.
```env: node\r: No such file or directory```

It has apparently to do with line endings on mac/unix systems.
I solved it for now by following this answer: http://stackoverflow.com/a/30349952
I had to run ```sudo dos2unix styleguide``` in my ```/usr/local/lib/node_modules/devbridge-styleguide/bin```

**Comment by kristenakamura** [comment]
Thanks for posting this! I was having the same issue.

**Comment by FynnZW** [comment]
Had the same issue, using node 5.10.1

This fixed it for me as well, thanks

**Comment by gediminas-s** [comment]
Thanks for notice, we will make an update on our end as well.

**Comment by jpserrett** [comment]
I just tried this fix with the most recent release version, and I am still getting this error: 
`env: node\r: No such file or directory`

I rand the `dos2unix` command, said it was successful, but I still get the error when running the `styleguide initialize` command.

**Comment by PizzaPete** [comment]
@jpserrett it is not yet fixed.
There was no release after @gediminas-s comment.

**Comment by jpserrett** [comment]
@PizzaPete I see that. I just wanted to put it out there that I wasn't able to get the same success as posted above, in case that helped any. 
Thanks for the update!

**Comment by nynban** [comment]
still says : no such file or directory, please help

**Comment by nynban** [comment]
env: node\r: No such file or directory

**Comment by laurenancona** [comment]
Thanks for building such an awesome tool.

FYI, getting same: `env: node\r: No such file or directory`

**Comment by JonnaIsaac01** [comment]
Agreed, thanks for the awesome tool, but I am also getting this error:
env: node\r: No such file or directory

I'm installing on a Mac OSX 10.11.4, using Gulp

Thanks!

**Comment by JonnaIsaac01** [comment]
As @mpons instructed, using dos2unix to convert the styleguide file inside of /bin did the trick.

I had to:
- Install Homebrew
- Use Homebrew to install dos2unix
- run sudo dos2unix styleguide in my /usr/local/lib/node_modules/devbridge-styleguide/bin

**Comment by nynban** [comment]
still get the same error: node\r: No such file or directory

**Comment by achord** [comment]
ditto

**Comment by kkashou** [comment]
Any updates on this? 

I am still getting this issue after using dos2unix.

**Comment by nynban** [comment]
same here, waiting for the update....... Does anyone know? Please help.  Thank you!

**Comment by fernandosouza** [comment]
Same error here.

**Comment by fernandosouza** [comment]
I resolved following the first comment of the thread by @mpons

**Comment by laurenancona** [comment]
Fix worked for me as well, thank you.

**Comment by edsu** [comment]
Any chance of releasing this fix to npm?

**Comment by VaclovasV** [comment]
@edsu this fix should already work. Are you still experiencing this?

**Comment by edsu** [comment]
Yes, I'm still experiencing it with [v0.4.9](https://www.npmjs.com/package/devbridge-styleguide), which was released 3 weeks ago:

```
env: node\r: No such file or directory
```

**Comment by miezis** [comment]
Ok, so line endings are correct, so I'm assuming, that node installed in your system is only accessible with nodejs, so my suggestion is to make a symlink or alias named node to nodejs location.

**Comment by edsu** [comment]
node is available: 

```
zen:x ed$ which node
/usr/local/bin/node
```

I think that the problem is that `node_modules/devbridge-styleguide/bin/styleguide` has DOS line endings. Did you see the '\r' in the error above? I realize that this is fixed here in GitHub. But it has not yet been released to npm, so someone following the instructions in the README.md will not get the fixed code.

**Comment by stevepiron** [comment]
**If the command dos2unix is not available, you have to install it first.**

Here's how to install dos2unix on Mac OSX: http://macappstore.org/dos2unix/ (if you already have Homebrew installed, jump to step 3).

Once both Homebrew and dos2unix are installed, you'll be able to run the command `styleguide initialize`. Hope this helps.

**Comment by VaclovasV** [comment]
New version is already published
