### ISSUE TITLE
Exemple

### ISSUE THREAD

**Issue by hamzazar** [devbridge/Styleguide#156]
I didn't succeed the initialisation, the installation instruction not detailed. Can someone please provide a  project example?

Thanks

**Comment by gediminas-s** [comment]
Could you give us more details about the steps you took.

**Comment by hamzazar** [comment]
I tied the integration in my project, added comments on my scss file etc.. But I didn't get the styleguide html files.

I need a very simple project scss + gruntfile so can see exactly how it works.

**Comment by VaclovasV** [comment]
@hamzazar  - what do you get after `styleguide initialize`?

**Comment by gediminas-s** [comment]
@hamzazar , did you use npm to install styleguide? Did you follow all the steps in the documentation https://github.com/devbridge/Styleguide/blob/master/README.md ?
After step 3 copy of the styleguide should be added to your project directory.

**Comment by gediminas-s** [comment]
@hamzazar, did you managed to make it work?

**Comment by VaclovasV** [comment]
Closing this, but feel free to re-open it and provide more details about the issue.
