### ISSUE TITLE
Integration of custom Web-Fonts

### ISSUE THREAD

**Issue by muggl** [devbridge/Styleguide#157]
Hi guys,

could anyone help me integrating my own font into the styleguide itself?
Tried to write it within the style.scss which you ll see on the mainpage - and I could also change the general body webfont within main.css. But within my .scss file the integration is not working. I still see sans-serif instead of my webfont.

Cause just the mention within this element block right here, does not locate my webfont file itself, right?

> //-- typo:start --//
> $font-myfont: 'MyFontName', myfont, sans-serif; // 300, 700
> //-- typo:end --//

Thanks in advance
Daniel

**Comment by valiooo** [comment]
Just to be clear, you want to change web fonts of the styleguide template itself. And if I understand correctly, you have difficulties compiling styleguide scss files?

**Comment by gediminas-s** [comment]
Just to be clear, you want to change web fonts of the styleguide template itself. And if I understand correctly, you have difficulties compiling styleguide scss files?

**Comment by gediminas-s** [comment]
no, you need to add web fonts references to your template.html file. 
![screenshot at may 30 11-00-56](https://cloud.githubusercontent.com/assets/10126531/15643394/d22a9b5e-2655-11e6-90be-e5b1a6d65885.png)

**Comment by muggl** [comment]
Oh man, yeah I totally forgot about that. 
I ll give it a try, thank you so much. I leave a reply if everything works fine :).

**Comment by muggl** [comment]
I still have no luck.

Well in order to test it, I tried to display the "font-awesome" font within my snippet on the main page.
( I do have a custom webfont in the same directory as font-awesome - just so I can see if font-awesome is loaded or not, then I change the file names correspondingly.

Here are some screenshots of my styles.scss and my templates.html.
![styles scss](https://cloud.githubusercontent.com/assets/19645054/15643767/64d0f374-264f-11e6-86d4-35628b48b70d.jpg)
![templateshtml](https://cloud.githubusercontent.com/assets/19645054/15643769/670cf782-264f-11e6-88a7-a260175ef708.jpg)

I want the font to be shown here:
![frontpage](https://cloud.githubusercontent.com/assets/19645054/15643778/71efaa3c-264f-11e6-9221-79d6e83d67a8.jpg)

Thank you

Daniel

**Comment by gediminas-s** [comment]
You can not declare @font-face inside `<style>` element. Try moving your css to external file.

**Comment by muggl** [comment]
Thanks mate, I got it for the actual template font to work well with my custom font.

But I still cant get the sass file to compile my webfont though. As you can see here, the text within the snippet is still "Lato", but beneath is my custom webfont.

![screen1](https://cloud.githubusercontent.com/assets/19645054/15644928/0b63d426-2656-11e6-90b4-fb7f53363713.jpg)

I tried to implement it within my styles.scss but I think I am missing one crusial thing.

The fonts.css works, but my styles.css isnt.

![styles scss](https://cloud.githubusercontent.com/assets/19645054/15644983/4d130388-2656-11e6-9676-8c6731a72478.jpg)
![fonts css](https://cloud.githubusercontent.com/assets/19645054/15644985/4e7daaf2-2656-11e6-9691-8ccac409e0bd.jpg)

Sorry for any inconvienence, just a beginner :)

**Comment by gediminas-s** [comment]
Could you send me your scss files, my guess is that you didn't apply "myFont-Sans..." font-family to h tags.

**Comment by muggl** [comment]
sure its pretty much empty ;P, but it works with the direct integration of (@import) google fonts, just not with my local files ...

**Comment by muggl** [comment]
I think I got everything correct now ... man ;P...reinstalled everything from scratch. I think now its working nicely. Thanks!

**Comment by gediminas-s** [comment]
Good to hear.
