### ISSUE TITLE
[Mac: Chrome] "Edit" controls always visible

### ISSUE THREAD

**Issue by yumyo** [devbridge/Styleguide#162]
Hi,

Chrome for Mac, appear to be the only browser to always render/show the "Edit" mode controls even if no styleguide server is running.
<img width="213" alt="screen shot 2016-05-31 at 17 01 14" src="https://cloud.githubusercontent.com/assets/959034/15681524/6b866ac0-2751-11e6-8ff5-97716051baa6.png">

OSX 10.11.5 (15F34)
Chrome Version 50.0.2661.102 (64-bit)

Opera, Firefox and Safari render it correctly (no Edit controls).

**Comment by nynban** [comment]
@yumyo I am using Mac Chrome but still doesnt show

**Comment by yumyo** [comment]
thanks for checking @nynban, however, I still see them. Could you check it [here](http://rcnt.eu/cjk)? Weird enough, browsershots.org shows no Edit controls. Wondering what could cause it in my environment.

**Comment by nynban** [comment]
@yumyo, i clicked on the link and no i dont see the edit mode

**Comment by yumyo** [comment]
Thanks @nynban 
So, it seems there's something wrong in my local environment. Still, can't guess what could cause it. Apart from extensions, there's no much left. Frustrating. I'm closing the issue by now.
