### ISSUE TITLE
Start scss scrape not working

### ISSUE THREAD

**Issue by JonnaIsaac01** [devbridge/Styleguide#167]
Hi,

First of all, thanks for this styleguide!

I've installed it in a local magento project, and everything appears to be working. I added the smart tags to my variable file, and updated the sassVariables in the config.txt file, however, when I click "Start Scss Scrape" nothing appears to happen. I tried variations to my sassVariables path, and, added a projectName, which displays as expected.

My current sassVariables path is (my theme being, 'baronessa')
"sassVariables": "skin/frontend/baronessa/default/scss/_var.scss",

Help please! 

Thanks,
Jonna

**Comment by kestas-devbridge** [comment]
Hi Jonna,

Config expects array as sassVariables. Please update your config to include brackets:
"sassVariables": ["skin/frontend/baronessa/default/scss/_var.scss"]

**Comment by JonnaIsaac01** [comment]
Hey Kestas,

Sorry, I had tried that as well, with the same result. I should've mentioned that.

Thanks.

**Comment by kestas-devbridge** [comment]
Hi Jonna,

Is there any errors in console after you click 'Start Scss Scrape'?

Also server reads sassVariables path on initialization so after changing path please restart server.

**Comment by JonnaIsaac01** [comment]
Hey Kestutis,

Restarting the server worked. Thanks for your help!

**Comment by kestas-devbridge** [comment]
Good to hear.
