### ISSUE TITLE
Remove uppercase letters and spaces from filenames of categories

### ISSUE THREAD

**Issue by andrius1** [devbridge/Styleguide#169]
For example, when I create category and name it "App Messages", styleguide saves database file as "App Messages.txt". Uppercase letters or spaces can cause problems with URL paths on some environments or git.

I think file name should be converted to something like "app_messages.txt".

**Comment by VaclovasV** [comment]
and from app_messages, how we will know, it is App Messages, App messages or app messages?

**Comment by andrius1** [comment]
Name of category should be stored as a string inside the .txt file, for example:

[
  {
    "categoryName": "App Messages",
   },
.... there goes snippets
]

**Comment by VaclovasV** [comment]
but naming is still a "first in a queue" file and naming is related with category name, so this is just a duplication :) Do you have existing issues with current implementation?

**Comment by andrius1** [comment]
Yep, we had problems when doing git merge. One person changed the snippets, other person changed the name of category (App messages -> App Messages), and git created two separate files.

Also, we have a problem, that somehow we have file "Layout elements.txt" and on the categories list it is stored as "Layout Elements". And that works perfectly on localhost, but it doesn't work when you run styleguide on other environment.

**Comment by VaclovasV** [comment]
First behavior is quite normal and this solution would not resolve issue.
About second - lets investigate, how these incorrect entries appeared and maybe this is already fixed. 
@miezis - maybe you are familiar with this or maybe it is already fixed?

**Comment by miezis** [comment]
This was not altered a long time. Maybe @andrius1 remembers how did he produce that?

**Comment by gediminas-s** [comment]
I guess is a matter of file naming good practices. I would vote for no spaces and lower case scenario. In regards of @VaclovasV example, all three names "App Messages", "App messages", "app messages" should be treated as duplicates.

**Comment by VaclovasV** [comment]
Closing this, reopen if needed.
