### ISSUE TITLE
Add success/error messsages if snippet is created/removed/edited

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Styleguide#17]

**Comment by miezis** [comment]
Done.

**Comment by tkirda** [comment]
Why is there no commit associated with the task?

**Comment by miezis** [comment]
It was partly implemented from the beginning. In commit: https://github.com/devbridge/Styleguide/commit/bcf2a3c2cc5e1c660c7eb949aaa6859d73906060

I added alert after snippet deletion.

**Comment by tkirda** [comment]
Best practice, is to include issue number in the commit message. You can also close the issue, e.g.:

    commit message..., fixes #17

This will close issue and reference commit.
