### ISSUE TITLE
FontAwesome not displaying?

### ISSUE THREAD

**Issue by zachatkinson** [devbridge/Styleguide#171]
I've noticed even on the main demo site FontAwesome doesn't seem to load 

http://styleguide.devbproto.com/styleguide/

(see top right)

Tested on Google Chrome 51.0.2704.103

**Comment by VaclovasV** [comment]
@gediminas-s - we should get rid of this library, because it has lots of issues.

**Comment by gediminas-s** [comment]
Already on the list for removal.

**Comment by dasmurphy** [comment]
As a workaround i downloaded the current version from their homepage and replaced the old one. That worked for me.

**Comment by uxmoon** [comment]
@dasmurphy I had to do the same. I've downloaded the fonts from the official web and replaced the font files.

**Comment by gediminas-s** [comment]
Replaced web fonts with svg icons.
