### ISSUE TITLE
Config not picking up sassVariables?

### ISSUE THREAD

**Issue by zachatkinson** [devbridge/Styleguide#173]
Hi guys,

Just trying to get the styleguide to scrape my variables, but it seems no matter how I write the path it doesn't find any "smart variables" inside. I have used the sample code included in the styleguide to no avail.  

Originally I had all my sass in a sub-folder labeled scss, but since that wasn't working I tried putting it in the root of the styleguide directory, still to no avail.  Any help is apreciated.  

My config:

    {
      "projectName": "CSF Race",
      "projectUrl": "http://csfrace.com",
      "projectLogo": "",
      "jsResources": [],
      "viewportWidths": [
        320,
        480,
        768,
        1024,
        1200
      ],
      "serverPort": 8889,
      "snippetTemplate": "styleguide\\template.html",
      "sassVariables": ["./_variables.scss"],
      "maxSassIterations": 2000,
      "database": "styleguide\\db",
      "categories": "styleguide\\db\\categories.txt",
      "uniques": "styleguide\\db\\uniques.txt",
      "sassData": "styleguide\\db\\sassdata.txt",
      "extension": ".txt"
    }

_variables.scss Contents:

    //-- colors:start --//
    $color-black: #000000;
    $color-dark: #141823;
    $red-lighter: #d26262;
    //-- colors:end --//
    
    //-- typo:start --//
    $font-proxima: 'Neue Helvetica W01', helvetica, sans-serif; // 300, 700
    $font-proxima-alternative: 'Neue Helvetica W01', helvetica, sans-serif; // 400, 400 italic
    $font-newsgothic: 'Neue Helvetica W01', helvetica, sans-serif; // 700
    //-- typo:end --//

And a screenshot of my file structure:
https://www.dropbox.com/s/lomqc27f7bw9iw0/filestruct.png?dl=0

NOTE: I have ensured both the styleguide server and live-server are running when attempting this, they did not rectify the issue.

**Comment by VaclovasV** [comment]
@zachatkinson, the issue is that you are including all your project inside styleguide directory instead putting styleguide and all your files in your project root directory. Place your variables file, near the node_modules and example should work. 
Use provided example:
"sassVariables": ['_variables.scss']

**Comment by zachatkinson** [comment]
That worked like a charm.  May I suggest this be mentioned in the docs?  Even suggesting users place the sass in the root and providing a sample relative path would be easier to understand than the current wording.  At any rate, thanks for the help and keep up the great work!
