### ISSUE TITLE
Scss variables path error - Unexpected token ' in JSON at position 283

### ISSUE THREAD

**Issue by ingevlaar** [devbridge/Styleguide#188]
I'm getting an error when I define the scss variables path in the config.txt. In the end I defined: 
"sassVariables": ['_variables.scss']

And placed the _variables.scss in the root, next to the node_modules folder.

and even used the contents of the styleguide example:
//-- typo:start --//
$font-proxima: 'Proxima Nova', helvetica, sans-serif; // 300, 700
$font-proxima-alternative: 'Neue Helvetica W01', helvetica, sans-serif; // 400, 400 italic
$font-newsgothic: 'News Gothic Std', helvetica, sans-serif; // 700
//-- typo:end --//
//-- colors:start --//
$color-black: #000000;
$color-dark: #141823;
$color-lighter-2: #d26262;
//-- colors:end --//

but still getting the error:

[10:04:17] SyntaxError: Unexpected token ' in JSON at position 283
    at Object.parse (native)
    at Object.exports.startServer (C:\Boilerplate-Frontend\dev\node
_modules\devbridge-styleguide\index.js:16:20)
    at Gulp.<anonymous> (C:\Boilerplate-Frontend\dev\gulpfile.js:47
:14)
    at module.exports (C:\Boilerplate-Frontend\dev\node_modules\orc
hestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Boilerplate-Frontend\dev\node
_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Boilerplate-Frontend\dev\node
_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Boilerplate-Frontend\dev\node_mo
dules\orchestrator\index.js:134:8)
    at C:\Users\***\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

I'm having Windows 8.1 and Nodejs v6.1.0

**Comment by miezis** [comment]
That's because you're using single quotes in JSON, it should be double quotes.

**Comment by ingevlaar** [comment]
Ah..., that is it!
In the example inside the styleguide is mentioned at step 2.

"Make sure you have scss file path defined in config:
{
  sassVariables: ['/scss/_variables.scss'],
  maxSassIterations: 2000
}"

and also on the github page:

"Next, declare scss file path references in styleguide config file:

"sassVariables": ['/path/to/your/project/scss/file.scss']"

Should be updated to double quotes then.

**Comment by VaclovasV** [comment]
Thank you! fixed documentation.

**Comment by Kiina** [comment]
It is still wrong in "templates/index.html" which you see when you first start it. Thats why I made a pull request like a month ago...

**Comment by gediminas-s** [comment]
My mistake, fixed. Thanks for notice.
