### ISSUE TITLE
Scss vars not visible when it is in other folder than styleguide

### ISSUE THREAD

**Issue by agbu** [devbridge/Styleguide#192]
Wen my styleguide is in other folder than scss vars file, i can't see it on styleguide.
config.txt:
"sassVariables": ["../resources/assets/sass/base/_vars.scss"],

![project-structure](https://cloud.githubusercontent.com/assets/2973829/17136697/950afe6e-533f-11e6-8443-a7f85c95170f.png)

**Comment by AndriusZid** [comment]
I think there is an issue with paths in different directories. We will try to fix this issue as soon as possible.

For now you can try edit your "sassVaribales" path like this:
`"sassVariables": ["./resources/assets/sass/base/_vars.scss"],`

and make sure you have right styleguidePath:
```
styleguide.startServer({
    styleguidePath: '/public/styleguide'
});
```
restart styleguide task and see if this works

**Comment by agbu** [comment]
I created second gulpfile.js to start styleguide on public folder, so i do not need another path. 

A solution with `"sassVariables": ["./resources/assets/sass/base/_vars.scss"],` sadly do not help.

**Comment by agbu** [comment]
I  don't know what i did different, but i created new styleguide on public and it gets my variables with `"sassVariables": ["../resources/assets/sass/base/_vars.scss"],`. Thant you for your attention and help.
It would be very good anyway, if i could have one gulpfile.js and package.json on root directory to generate styleguide in another folder.

**Comment by gediminas-s** [comment]
I was able to recreate and run a scrape by setting parent paths:
<img width="1377" alt="screenshot at jul 26 16-25-00" src="https://cloud.githubusercontent.com/assets/10126531/17140144/08266d06-5350-11e6-95d2-33e58c205042.png">

**Comment by gediminas-s** [comment]
We going to review our path logic and make some changes. This getting complicated :)

**Comment by gediminas-s** [comment]
Closing this one, please reopen if issue still arise.
