### ISSUE TITLE
create category file

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Styleguide#2]
Categories will be manages by config file. 
Each category going to have separate file in which snippets information will be held. 
On client side going to be list of categories in the header for navigation between the pages.

![screenshot at may 14 16-53-47](https://cloud.githubusercontent.com/assets/10126531/7632953/d8988ce0-fa59-11e4-8a03-5da0f685c10f.png)

**Comment by miezis** [comment]
Done.
