### ISSUE TITLE
Check viewport assigment function if it returns correct results

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Styleguide#21]
http://stackoverflow.com/questions/19291873/window-width-not-the-same-as-media-query

**Comment by miezis** [comment]
https://github.com/devbridge/Styleguide/commit/11508d16ba5a737c7da3b00461ab0a072691bb68

Changed assignment of viewport for iframe, so that inputs would be accurate to debug media-queries.

Needs styling, so that outer div would be the sizes of the iframe and in center.
