### ISSUE TITLE
Add class to body element, to create pseudo element on iframe, preventing going in to another "document" object 

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Styleguide#23]
Then resizing, go oonto iframe area and you will see, that window is not resizing. we need pseudo element, to prevent entering different "document"

**Comment by VaclovasV** [comment]
After task is finished, assign to front-end developer

**Comment by miezis** [comment]
https://github.com/devbridge/Styleguide/commit/f9d202b91f560c263742bbadece62a905b13e686

There is a div sibling to iframe injected when drawing snippets. Every time you move interactjs handles a iframe-overlay class is added to that div. It needs styling to overlay iframe content.

**Comment by gediminas-s** [comment]
Need testing
