### ISSUE TITLE
Add crawl summary after crawling is succedded

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Styleguide#29]
Add modal window, with following information:
New snippets found
Changed snippets
Dublicate ids
Total snippets found

**Comment by miezis** [comment]
isEdited: true, doesnt include in changed snippets.

**Comment by miezis** [comment]
changes snippets contain only snippets that code is changed. (compare hashes).
only report if duplicate ids in scraped code are found, continue writing out, just report that.
New snippets - only count of newly added snippets to code.
