### ISSUE TITLE
Add Sass data summary after scrape is done.

### ISSUE THREAD

**Issue by miezis** [devbridge/Styleguide#33]
Add modal, which shows how many unique hex(rgba, etc..) values were added and removed.
Indicate if typography vars were changed and if changed - then what changed?

**Comment by miezis** [comment]
values were added - count of variable values scraped. removed -diff.

if typography object is changed, on one side show old typo, on other new typo.

**Comment by miezis** [comment]
https://github.com/devbridge/Styleguide/commit/a84d55a30612ca0afde4c0c32bbc2c3f8a8547d2

Need to style typo-summary-old and typo-summary-new classes, that are in modal after scrape. typo-summary-old should be on the left side and the typo-summary-new on the right at same level.

**Comment by gediminas-s** [comment]
Need testing

**Comment by gediminas-s** [comment]
Lets just show simple message. 
![screenshot at feb 02 16-54-23](https://cloud.githubusercontent.com/assets/10126531/12753114/4b633768-c9ce-11e5-8c5b-1749ba5f61cd.png)
