### ISSUE TITLE
Clean up config

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Styleguide#45]
We need to include CSS resources into config file as manditory option because without CSS Styleguide component becomes useless. All other options could have default values and would be as optional options.

To have Styleguide up and running user would have minimal config like this:

```json
{
    "cssResources":[
        "/site.css",
        "/webfonts.css"
    ]
  }
```

Full config with default options:

```json
{
  "cssResources":[],
  "jsResources": [],
  "categories": [
    {
      "name": "undefined",
      "id": 0
    }
  ],
  "scrapeUrls": [],
  "sassVariables": [], //renamed from sassResources  
  "resolutions": [
    1200,1024,768,480,320  //removed naming
  ],
  "database": "styleguide/db",
  "uniques": "styleguide/db/uniques.txt",
  "sassData": "styleguide/db/sassdata.txt",
  "extension": ".txt",
  "maxSassIterations": 3,
  "snippetTemplate": "styleguide/template.html",
  "serverPort": 8000
}
```

**Comment by gediminas-s** [comment]
Agreed to have one config file in styleguide root directory. Additional properties for config:
projectName, projectUrl, projectLogo

**Comment by miezis** [comment]
Configuration unified, also added additional properties for project information and showing that information in home page.

Need testing.
