### ISSUE TITLE
Remove global styling or add it to namespaced elements only

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Styleguide#53]
For example:
http://prntscr.com/9f7vyv
http://prntscr.com/9f7w7v
http://prntscr.com/9f7wa5
http://prntscr.com/9f7wem
http://prntscr.com/9f7wo8

and etc

**Comment by gediminas-s** [comment]
This issue is related to iframe and isolating project styles from Styleguide template.

**Comment by gediminas-s** [comment]
Not relevant anymore because all project resources isolated by iframe.
