### ISSUE TITLE
Copy snippet code is not working

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Styleguide#58]
![image](https://cloud.githubusercontent.com/assets/3501072/11891130/405ac1ee-a564-11e5-9998-90f5aff3b6f5.png)

**Comment by gediminas-s** [comment]
Works for me, tested on mac. Confirmation message is messing.

**Comment by gediminas-s** [comment]
Lets move to js only approach https://clipboardjs.com/

**Comment by linasmatakas** [comment]
replaced plugin, but I am not sure if it works on Mac Safari.

**Comment by gediminas-s** [comment]
Doesn't work on safari, any solution?
