### ISSUE TITLE
Create UI for category creation

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Styleguide#72]

**Comment by gediminas-s** [comment]
![ozrmg58](https://cloud.githubusercontent.com/assets/10126531/12670415/f8a912b4-c670-11e5-8807-d27a5da32209.png)

**Comment by gediminas-s** [comment]
![screenshot at jan 29 10-48-32](https://cloud.githubusercontent.com/assets/10126531/12671097/14568118-c676-11e5-8304-4529e3d64619.png)
![screenshot at jan 29 10-49-49](https://cloud.githubusercontent.com/assets/10126531/12671098/1459993e-c676-11e5-89cc-b8b2e3ddf4fd.png)

**Comment by gediminas-s** [comment]
UI has been implemented. Now, we need to hook up functionality.

**Comment by miezis** [comment]
Functionality hooked up, need to test if everything works as expected.
