### ISSUE TITLE
Update styles on general page fonts section 

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Styleguide#74]
Fonts section should inherit only following styles:
- Font family
- font weight 
- font style

NO color or font size should be inherited.
![screenshot at jan 11 17-11-13](https://cloud.githubusercontent.com/assets/10126531/12237423/484aa500-b887-11e5-8426-4a53586e533d.png)

And why we have two iframes for each font?
![screenshot at jan 11 17-12-03](https://cloud.githubusercontent.com/assets/10126531/12237447/620a0d64-b887-11e5-8a92-df10359859b1.png)

**Comment by linasmatakas** [comment]
There are two iframes, because of layout for font info, 'aa' and alphabet. Also font info has some styleguide's styling and I do not think it should have project's styling and font.

**Comment by linasmatakas** [comment]
Added extra styling to prevent font size or color inheritance.
