### ISSUE TITLE
Update scrapped Scss is not working 

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Styleguide#78]
When you try to update scraped variables i receive following error:
The only way to scrape variable again I need to restart server.
![screenshot at feb 02 13-43-05](https://cloud.githubusercontent.com/assets/10126531/12748478/27f49634-c9b3-11e5-9fa3-cded905d9b6c.png)

**Comment by gediminas-s** [comment]
I found a reason, sassdata.txt file can not be empty. It must have at least empty brackets []. Can we through more descriptive error?

**Comment by miezis** [comment]
Fixed this - if sassdata.txt is empty - create an empty array. This was used for snippet scrapping, probabbly missed sass scraping when I was fixing snippet scrapping.

Needs testing.
