### ISSUE TITLE
Scrape variables functionality issue

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Styleguide#93]
I unable to complete scrape (get error) if one of declarations (color or type) do not exist in my variables files. 
We should allow to scrape variables even if only one type of declarations exists. On general page we should show only sections that have data (colors, fonts). Also, make sure that multiple files can be scraped.

**Comment by miezis** [comment]
Could you provide variables files content for better understanding of the problem?

**Comment by gediminas-s** [comment]
On db.com we have two separate files for variables, one contains colors and another one other variables.  

[Archive.zip](https://github.com/devbridge/Styleguide/files/124626/Archive.zip)

**Comment by gediminas-s** [comment]
Also, I can see scenario when only one type of variables (color or type) going to be used per project.

**Comment by miezis** [comment]
I managed to fixed the bugs: One was caused by extended Array type and another one by incorecct checking if typography changed. For now variable files should be scraped correctly.

Still need to combine variables from separate files.

**Comment by miezis** [comment]
Results form separate files are concatenated into final result now.

Needs testing.

**Comment by gediminas-s** [comment]
I still receive error. 
I have two scss files that contains one different type of declarations (file one - colors, file two - fonts)
![screenshot at feb 29 13-25-09](https://cloud.githubusercontent.com/assets/10126531/13393082/e2ab2436-dee7-11e5-8f21-df3475e71fc8.png)
